name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          # This tells setup-node to automatically write the token to .npmrc
          # which guarantees the publish step will find it.
          always-auth: true

      - name: Install Dependencies
        run: npm ci

      - name: Build Node
        run: npm run build

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          # This variable MUST match the name of the secret in your GitHub repo
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
